### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by perhedeland** [grembo/xorg-udev-setup-check#1]
Reading the script (after running it:-) I think I spotted a minor bug
(wasn't triggered when I ran it):

\--------------------
xf86-input-synaptics is installed.

This can interfere with xf86-input-libinput, please remove using

pkg delete xf86-input-libinput
\--------------------

Presumably that should be 'pkg delete xf86-input-synaptics'.

**Comment by grembo** [comment]
Thanks!
